import { z } from "zod";

import { boolWithDefault, optEmail, optText, reqText, uuidRef } from "./_shared";
import { PARTY_STATUSES } from "./consignees";

export const shipperCreateSchema = z.object({
  code: reqText("Code", 50),
  name: reqText("Name", 200),
  origin_id: uuidRef(),
  origin_code: optText(50),
  contact_person: optText(200),
  address1: optText(500),
  address2: optText(500),
  telephone1: optText(30),
  telephone2: optText(30),
  fax: optText(30),
  industry_id: uuidRef(),
  iec_no: optText(50),
  gst_no: optText(50),
  aadhar_no: optText(30),
  pan_no: optText(30),
  service_center_id: uuidRef(),
  service_center_code: optText(50),
  bank_ad_code: optText(50),
  bank_account: optText(50),
  bank_ifsc: optText(20),
  firm: optText(50),
  nfei: boolWithDefault(false),
  lut_number: optText(50),
  lut_issue_date: optText(20),
  lut_till_date: optText(20),
  customer_id: uuidRef(),
  customer_name: optText(200),
  mobile: reqText("Mobile", 30),
  email: optEmail(),
  address: optText(500),
  pin_code: optText(20),
  city: optText(100),
  state_id: uuidRef(),
  state_name: optText(100),
  country_id: uuidRef(),
  status: z.enum(PARTY_STATUSES).default("ACTIVE"),
});

export const shipperUpdateSchema = shipperCreateSchema.partial();

export type ShipperCreate = z.infer<typeof shipperCreateSchema>;
export type ShipperUpdate = z.infer<typeof shipperUpdateSchema>;

export const shipperDefaults: Partial<z.input<typeof shipperCreateSchema>> = {
  code: "",
  name: "",
  origin_code: "",
  origin_id: "",
  contact_person: "",
  address1: "",
  address2: "",
  telephone1: "",
  telephone2: "",
  fax: "",
  industry_id: "",
  iec_no: "",
  gst_no: "",
  aadhar_no: "",
  pan_no: "",
  service_center_id: "",
  service_center_code: "",
  bank_ad_code: "",
  bank_account: "",
  bank_ifsc: "",
  firm: "",
  nfei: false,
  lut_number: "",
  lut_issue_date: "",
  lut_till_date: "",
  customer_name: "",
  customer_id: "",
  mobile: "",
  email: "",
  address: "",
  pin_code: "",
  city: "",
  state_id: "",
  state_name: "",
  country_id: "",
  status: "ACTIVE",
};
