/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionPickupInscanRouteImport } from './routes/transaction.pickup-inscan'
import { Route as TransactionPickupRouteImport } from './routes/transaction.pickup'
import { Route as TransactionManifestViewRouteImport } from './routes/transaction.manifest-view'
import { Route as TransactionManifestScanRouteImport } from './routes/transaction.manifest-scan'
import { Route as TransactionManifestInScanRouteImport } from './routes/transaction.manifest-in-scan'
import { Route as TransactionAwbEntryRouteImport } from './routes/transaction.awb-entry'
import { Route as TransactionSplatRouteImport } from './routes/transaction.$'
import { Route as ReportsSplatRouteImport } from './routes/reports.$'
import { Route as MasterSplatRouteImport } from './routes/master.$'
import { Route as MasterVendorVendorContractRouteImport } from './routes/master.vendor.vendor-contract'
import { Route as MasterVendorVendorRouteImport } from './routes/master.vendor.vendor'
import { Route as MasterSalesZoneRouteImport } from './routes/master.sales.zone'
import { Route as MasterSalesStateRouteImport } from './routes/master.sales.state'
import { Route as MasterSalesServiceCenterRouteImport } from './routes/master.sales.service-center'
import { Route as MasterSalesSalesExecutiveRouteImport } from './routes/master.sales.sales-executive'
import { Route as MasterSalesProductTypeRouteImport } from './routes/master.sales.product-type'
import { Route as MasterSalesProductRouteImport } from './routes/master.sales.product'
import { Route as MasterSalesLocalBranchRouteImport } from './routes/master.sales.local-branch'
import { Route as MasterSalesInstructionRouteImport } from './routes/master.sales.instruction'
import { Route as MasterSalesIndustryRouteImport } from './routes/master.sales.industry'
import { Route as MasterSalesFlightRouteImport } from './routes/master.sales.flight'
import { Route as MasterSalesDestinationRouteImport } from './routes/master.sales.destination'
import { Route as MasterSalesCountryRouteImport } from './routes/master.sales.country'
import { Route as MasterSalesContentRouteImport } from './routes/master.sales.content'
import { Route as MasterSalesChargesMasterRouteImport } from './routes/master.sales.charges-master'
import { Route as MasterSalesBankMasterRouteImport } from './routes/master.sales.bank-master'
import { Route as MasterOperationServiceMappingRouteImport } from './routes/master.operation.service-mapping'
import { Route as MasterOperationPinCodeRouteImport } from './routes/master.operation.pin-code'
import { Route as MasterOperationFieldExecutiveRouteImport } from './routes/master.operation.field-executive'
import { Route as MasterOperationExceptionRouteImport } from './routes/master.operation.exception'
import { Route as MasterOperationCountryPincodesRouteImport } from './routes/master.operation.country-pincodes'
import { Route as MasterOperationAreaRouteImport } from './routes/master.operation.area'
import { Route as MasterOperationAirlineRouteImport } from './routes/master.operation.airline'
import { Route as MasterCustomerShipperRouteImport } from './routes/master.customer.shipper'
import { Route as MasterCustomerExpenseRouteImport } from './routes/master.customer.expense'
import { Route as MasterCustomerCustomerRateRouteImport } from './routes/master.customer.customer-rate'
import { Route as MasterCustomerCustomerRouteImport } from './routes/master.customer.customer'
import { Route as MasterCustomerConsigneeRouteImport } from './routes/master.customer.consignee'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionPickupInscanRoute = TransactionPickupInscanRouteImport.update({
  id: '/transaction/pickup-inscan',
  path: '/transaction/pickup-inscan',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionPickupRoute = TransactionPickupRouteImport.update({
  id: '/transaction/pickup',
  path: '/transaction/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionManifestViewRoute = TransactionManifestViewRouteImport.update({
  id: '/transaction/manifest-view',
  path: '/transaction/manifest-view',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionManifestScanRoute = TransactionManifestScanRouteImport.update({
  id: '/transaction/manifest-scan',
  path: '/transaction/manifest-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionManifestInScanRoute =
  TransactionManifestInScanRouteImport.update({
    id: '/transaction/manifest-in-scan',
    path: '/transaction/manifest-in-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionAwbEntryRoute = TransactionAwbEntryRouteImport.update({
  id: '/transaction/awb-entry',
  path: '/transaction/awb-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionSplatRoute = TransactionSplatRouteImport.update({
  id: '/transaction/$',
  path: '/transaction/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSplatRoute = ReportsSplatRouteImport.update({
  id: '/reports/$',
  path: '/reports/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSplatRoute = MasterSplatRouteImport.update({
  id: '/master/$',
  path: '/master/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterVendorVendorContractRoute =
  MasterVendorVendorContractRouteImport.update({
    id: '/master/vendor/vendor-contract',
    path: '/master/vendor/vendor-contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterVendorVendorRoute = MasterVendorVendorRouteImport.update({
  id: '/master/vendor/vendor',
  path: '/master/vendor/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesZoneRoute = MasterSalesZoneRouteImport.update({
  id: '/master/sales/zone',
  path: '/master/sales/zone',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesStateRoute = MasterSalesStateRouteImport.update({
  id: '/master/sales/state',
  path: '/master/sales/state',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesServiceCenterRoute =
  MasterSalesServiceCenterRouteImport.update({
    id: '/master/sales/service-center',
    path: '/master/sales/service-center',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterSalesSalesExecutiveRoute =
  MasterSalesSalesExecutiveRouteImport.update({
    id: '/master/sales/sales-executive',
    path: '/master/sales/sales-executive',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterSalesProductTypeRoute = MasterSalesProductTypeRouteImport.update({
  id: '/master/sales/product-type',
  path: '/master/sales/product-type',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesProductRoute = MasterSalesProductRouteImport.update({
  id: '/master/sales/product',
  path: '/master/sales/product',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesLocalBranchRoute = MasterSalesLocalBranchRouteImport.update({
  id: '/master/sales/local-branch',
  path: '/master/sales/local-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesInstructionRoute = MasterSalesInstructionRouteImport.update({
  id: '/master/sales/instruction',
  path: '/master/sales/instruction',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesIndustryRoute = MasterSalesIndustryRouteImport.update({
  id: '/master/sales/industry',
  path: '/master/sales/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesFlightRoute = MasterSalesFlightRouteImport.update({
  id: '/master/sales/flight',
  path: '/master/sales/flight',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesDestinationRoute = MasterSalesDestinationRouteImport.update({
  id: '/master/sales/destination',
  path: '/master/sales/destination',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesCountryRoute = MasterSalesCountryRouteImport.update({
  id: '/master/sales/country',
  path: '/master/sales/country',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesContentRoute = MasterSalesContentRouteImport.update({
  id: '/master/sales/content',
  path: '/master/sales/content',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSalesChargesMasterRoute =
  MasterSalesChargesMasterRouteImport.update({
    id: '/master/sales/charges-master',
    path: '/master/sales/charges-master',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterSalesBankMasterRoute = MasterSalesBankMasterRouteImport.update({
  id: '/master/sales/bank-master',
  path: '/master/sales/bank-master',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterOperationServiceMappingRoute =
  MasterOperationServiceMappingRouteImport.update({
    id: '/master/operation/service-mapping',
    path: '/master/operation/service-mapping',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterOperationPinCodeRoute = MasterOperationPinCodeRouteImport.update({
  id: '/master/operation/pin-code',
  path: '/master/operation/pin-code',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterOperationFieldExecutiveRoute =
  MasterOperationFieldExecutiveRouteImport.update({
    id: '/master/operation/field-executive',
    path: '/master/operation/field-executive',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterOperationExceptionRoute =
  MasterOperationExceptionRouteImport.update({
    id: '/master/operation/exception',
    path: '/master/operation/exception',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterOperationCountryPincodesRoute =
  MasterOperationCountryPincodesRouteImport.update({
    id: '/master/operation/country-pincodes',
    path: '/master/operation/country-pincodes',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterOperationAreaRoute = MasterOperationAreaRouteImport.update({
  id: '/master/operation/area',
  path: '/master/operation/area',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterOperationAirlineRoute = MasterOperationAirlineRouteImport.update({
  id: '/master/operation/airline',
  path: '/master/operation/airline',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCustomerShipperRoute = MasterCustomerShipperRouteImport.update({
  id: '/master/customer/shipper',
  path: '/master/customer/shipper',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCustomerExpenseRoute = MasterCustomerExpenseRouteImport.update({
  id: '/master/customer/expense',
  path: '/master/customer/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCustomerCustomerRateRoute =
  MasterCustomerCustomerRateRouteImport.update({
    id: '/master/customer/customer-rate',
    path: '/master/customer/customer-rate',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterCustomerCustomerRoute = MasterCustomerCustomerRouteImport.update({
  id: '/master/customer/customer',
  path: '/master/customer/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCustomerConsigneeRoute = MasterCustomerConsigneeRouteImport.update({
  id: '/master/customer/consignee',
  path: '/master/customer/consignee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/master/$': typeof MasterSplatRoute
  '/reports/$': typeof ReportsSplatRoute
  '/transaction/$': typeof TransactionSplatRoute
  '/transaction/awb-entry': typeof TransactionAwbEntryRoute
  '/transaction/manifest-in-scan': typeof TransactionManifestInScanRoute
  '/transaction/manifest-scan': typeof TransactionManifestScanRoute
  '/transaction/manifest-view': typeof TransactionManifestViewRoute
  '/transaction/pickup': typeof TransactionPickupRoute
  '/transaction/pickup-inscan': typeof TransactionPickupInscanRoute
  '/master/customer/consignee': typeof MasterCustomerConsigneeRoute
  '/master/customer/customer': typeof MasterCustomerCustomerRoute
  '/master/customer/customer-rate': typeof MasterCustomerCustomerRateRoute
  '/master/customer/expense': typeof MasterCustomerExpenseRoute
  '/master/customer/shipper': typeof MasterCustomerShipperRoute
  '/master/operation/airline': typeof MasterOperationAirlineRoute
  '/master/operation/area': typeof MasterOperationAreaRoute
  '/master/operation/country-pincodes': typeof MasterOperationCountryPincodesRoute
  '/master/operation/exception': typeof MasterOperationExceptionRoute
  '/master/operation/field-executive': typeof MasterOperationFieldExecutiveRoute
  '/master/operation/pin-code': typeof MasterOperationPinCodeRoute
  '/master/operation/service-mapping': typeof MasterOperationServiceMappingRoute
  '/master/sales/bank-master': typeof MasterSalesBankMasterRoute
  '/master/sales/charges-master': typeof MasterSalesChargesMasterRoute
  '/master/sales/content': typeof MasterSalesContentRoute
  '/master/sales/country': typeof MasterSalesCountryRoute
  '/master/sales/destination': typeof MasterSalesDestinationRoute
  '/master/sales/flight': typeof MasterSalesFlightRoute
  '/master/sales/industry': typeof MasterSalesIndustryRoute
  '/master/sales/instruction': typeof MasterSalesInstructionRoute
  '/master/sales/local-branch': typeof MasterSalesLocalBranchRoute
  '/master/sales/product': typeof MasterSalesProductRoute
  '/master/sales/product-type': typeof MasterSalesProductTypeRoute
  '/master/sales/sales-executive': typeof MasterSalesSalesExecutiveRoute
  '/master/sales/service-center': typeof MasterSalesServiceCenterRoute
  '/master/sales/state': typeof MasterSalesStateRoute
  '/master/sales/zone': typeof MasterSalesZoneRoute
  '/master/vendor/vendor': typeof MasterVendorVendorRoute
  '/master/vendor/vendor-contract': typeof MasterVendorVendorContractRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/master/$': typeof MasterSplatRoute
  '/reports/$': typeof ReportsSplatRoute
  '/transaction/$': typeof TransactionSplatRoute
  '/transaction/awb-entry': typeof TransactionAwbEntryRoute
  '/transaction/manifest-in-scan': typeof TransactionManifestInScanRoute
  '/transaction/manifest-scan': typeof TransactionManifestScanRoute
  '/transaction/manifest-view': typeof TransactionManifestViewRoute
  '/transaction/pickup': typeof TransactionPickupRoute
  '/transaction/pickup-inscan': typeof TransactionPickupInscanRoute
  '/master/customer/consignee': typeof MasterCustomerConsigneeRoute
  '/master/customer/customer': typeof MasterCustomerCustomerRoute
  '/master/customer/customer-rate': typeof MasterCustomerCustomerRateRoute
  '/master/customer/expense': typeof MasterCustomerExpenseRoute
  '/master/customer/shipper': typeof MasterCustomerShipperRoute
  '/master/operation/airline': typeof MasterOperationAirlineRoute
  '/master/operation/area': typeof MasterOperationAreaRoute
  '/master/operation/country-pincodes': typeof MasterOperationCountryPincodesRoute
  '/master/operation/exception': typeof MasterOperationExceptionRoute
  '/master/operation/field-executive': typeof MasterOperationFieldExecutiveRoute
  '/master/operation/pin-code': typeof MasterOperationPinCodeRoute
  '/master/operation/service-mapping': typeof MasterOperationServiceMappingRoute
  '/master/sales/bank-master': typeof MasterSalesBankMasterRoute
  '/master/sales/charges-master': typeof MasterSalesChargesMasterRoute
  '/master/sales/content': typeof MasterSalesContentRoute
  '/master/sales/country': typeof MasterSalesCountryRoute
  '/master/sales/destination': typeof MasterSalesDestinationRoute
  '/master/sales/flight': typeof MasterSalesFlightRoute
  '/master/sales/industry': typeof MasterSalesIndustryRoute
  '/master/sales/instruction': typeof MasterSalesInstructionRoute
  '/master/sales/local-branch': typeof MasterSalesLocalBranchRoute
  '/master/sales/product': typeof MasterSalesProductRoute
  '/master/sales/product-type': typeof MasterSalesProductTypeRoute
  '/master/sales/sales-executive': typeof MasterSalesSalesExecutiveRoute
  '/master/sales/service-center': typeof MasterSalesServiceCenterRoute
  '/master/sales/state': typeof MasterSalesStateRoute
  '/master/sales/zone': typeof MasterSalesZoneRoute
  '/master/vendor/vendor': typeof MasterVendorVendorRoute
  '/master/vendor/vendor-contract': typeof MasterVendorVendorContractRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/master/$': typeof MasterSplatRoute
  '/reports/$': typeof ReportsSplatRoute
  '/transaction/$': typeof TransactionSplatRoute
  '/transaction/awb-entry': typeof TransactionAwbEntryRoute
  '/transaction/manifest-in-scan': typeof TransactionManifestInScanRoute
  '/transaction/manifest-scan': typeof TransactionManifestScanRoute
  '/transaction/manifest-view': typeof TransactionManifestViewRoute
  '/transaction/pickup': typeof TransactionPickupRoute
  '/transaction/pickup-inscan': typeof TransactionPickupInscanRoute
  '/master/customer/consignee': typeof MasterCustomerConsigneeRoute
  '/master/customer/customer': typeof MasterCustomerCustomerRoute
  '/master/customer/customer-rate': typeof MasterCustomerCustomerRateRoute
  '/master/customer/expense': typeof MasterCustomerExpenseRoute
  '/master/customer/shipper': typeof MasterCustomerShipperRoute
  '/master/operation/airline': typeof MasterOperationAirlineRoute
  '/master/operation/area': typeof MasterOperationAreaRoute
  '/master/operation/country-pincodes': typeof MasterOperationCountryPincodesRoute
  '/master/operation/exception': typeof MasterOperationExceptionRoute
  '/master/operation/field-executive': typeof MasterOperationFieldExecutiveRoute
  '/master/operation/pin-code': typeof MasterOperationPinCodeRoute
  '/master/operation/service-mapping': typeof MasterOperationServiceMappingRoute
  '/master/sales/bank-master': typeof MasterSalesBankMasterRoute
  '/master/sales/charges-master': typeof MasterSalesChargesMasterRoute
  '/master/sales/content': typeof MasterSalesContentRoute
  '/master/sales/country': typeof MasterSalesCountryRoute
  '/master/sales/destination': typeof MasterSalesDestinationRoute
  '/master/sales/flight': typeof MasterSalesFlightRoute
  '/master/sales/industry': typeof MasterSalesIndustryRoute
  '/master/sales/instruction': typeof MasterSalesInstructionRoute
  '/master/sales/local-branch': typeof MasterSalesLocalBranchRoute
  '/master/sales/product': typeof MasterSalesProductRoute
  '/master/sales/product-type': typeof MasterSalesProductTypeRoute
  '/master/sales/sales-executive': typeof MasterSalesSalesExecutiveRoute
  '/master/sales/service-center': typeof MasterSalesServiceCenterRoute
  '/master/sales/state': typeof MasterSalesStateRoute
  '/master/sales/zone': typeof MasterSalesZoneRoute
  '/master/vendor/vendor': typeof MasterVendorVendorRoute
  '/master/vendor/vendor-contract': typeof MasterVendorVendorContractRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/master/$'
    | '/reports/$'
    | '/transaction/$'
    | '/transaction/awb-entry'
    | '/transaction/manifest-in-scan'
    | '/transaction/manifest-scan'
    | '/transaction/manifest-view'
    | '/transaction/pickup'
    | '/transaction/pickup-inscan'
    | '/master/customer/consignee'
    | '/master/customer/customer'
    | '/master/customer/customer-rate'
    | '/master/customer/expense'
    | '/master/customer/shipper'
    | '/master/operation/airline'
    | '/master/operation/area'
    | '/master/operation/country-pincodes'
    | '/master/operation/exception'
    | '/master/operation/field-executive'
    | '/master/operation/pin-code'
    | '/master/operation/service-mapping'
    | '/master/sales/bank-master'
    | '/master/sales/charges-master'
    | '/master/sales/content'
    | '/master/sales/country'
    | '/master/sales/destination'
    | '/master/sales/flight'
    | '/master/sales/industry'
    | '/master/sales/instruction'
    | '/master/sales/local-branch'
    | '/master/sales/product'
    | '/master/sales/product-type'
    | '/master/sales/sales-executive'
    | '/master/sales/service-center'
    | '/master/sales/state'
    | '/master/sales/zone'
    | '/master/vendor/vendor'
    | '/master/vendor/vendor-contract'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/master/$'
    | '/reports/$'
    | '/transaction/$'
    | '/transaction/awb-entry'
    | '/transaction/manifest-in-scan'
    | '/transaction/manifest-scan'
    | '/transaction/manifest-view'
    | '/transaction/pickup'
    | '/transaction/pickup-inscan'
    | '/master/customer/consignee'
    | '/master/customer/customer'
    | '/master/customer/customer-rate'
    | '/master/customer/expense'
    | '/master/customer/shipper'
    | '/master/operation/airline'
    | '/master/operation/area'
    | '/master/operation/country-pincodes'
    | '/master/operation/exception'
    | '/master/operation/field-executive'
    | '/master/operation/pin-code'
    | '/master/operation/service-mapping'
    | '/master/sales/bank-master'
    | '/master/sales/charges-master'
    | '/master/sales/content'
    | '/master/sales/country'
    | '/master/sales/destination'
    | '/master/sales/flight'
    | '/master/sales/industry'
    | '/master/sales/instruction'
    | '/master/sales/local-branch'
    | '/master/sales/product'
    | '/master/sales/product-type'
    | '/master/sales/sales-executive'
    | '/master/sales/service-center'
    | '/master/sales/state'
    | '/master/sales/zone'
    | '/master/vendor/vendor'
    | '/master/vendor/vendor-contract'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/master/$'
    | '/reports/$'
    | '/transaction/$'
    | '/transaction/awb-entry'
    | '/transaction/manifest-in-scan'
    | '/transaction/manifest-scan'
    | '/transaction/manifest-view'
    | '/transaction/pickup'
    | '/transaction/pickup-inscan'
    | '/master/customer/consignee'
    | '/master/customer/customer'
    | '/master/customer/customer-rate'
    | '/master/customer/expense'
    | '/master/customer/shipper'
    | '/master/operation/airline'
    | '/master/operation/area'
    | '/master/operation/country-pincodes'
    | '/master/operation/exception'
    | '/master/operation/field-executive'
    | '/master/operation/pin-code'
    | '/master/operation/service-mapping'
    | '/master/sales/bank-master'
    | '/master/sales/charges-master'
    | '/master/sales/content'
    | '/master/sales/country'
    | '/master/sales/destination'
    | '/master/sales/flight'
    | '/master/sales/industry'
    | '/master/sales/instruction'
    | '/master/sales/local-branch'
    | '/master/sales/product'
    | '/master/sales/product-type'
    | '/master/sales/sales-executive'
    | '/master/sales/service-center'
    | '/master/sales/state'
    | '/master/sales/zone'
    | '/master/vendor/vendor'
    | '/master/vendor/vendor-contract'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  MasterSplatRoute: typeof MasterSplatRoute
  ReportsSplatRoute: typeof ReportsSplatRoute
  TransactionSplatRoute: typeof TransactionSplatRoute
  TransactionAwbEntryRoute: typeof TransactionAwbEntryRoute
  TransactionManifestInScanRoute: typeof TransactionManifestInScanRoute
  TransactionManifestScanRoute: typeof TransactionManifestScanRoute
  TransactionManifestViewRoute: typeof TransactionManifestViewRoute
  TransactionPickupRoute: typeof TransactionPickupRoute
  TransactionPickupInscanRoute: typeof TransactionPickupInscanRoute
  MasterCustomerConsigneeRoute: typeof MasterCustomerConsigneeRoute
  MasterCustomerCustomerRoute: typeof MasterCustomerCustomerRoute
  MasterCustomerCustomerRateRoute: typeof MasterCustomerCustomerRateRoute
  MasterCustomerExpenseRoute: typeof MasterCustomerExpenseRoute
  MasterCustomerShipperRoute: typeof MasterCustomerShipperRoute
  MasterOperationAirlineRoute: typeof MasterOperationAirlineRoute
  MasterOperationAreaRoute: typeof MasterOperationAreaRoute
  MasterOperationCountryPincodesRoute: typeof MasterOperationCountryPincodesRoute
  MasterOperationExceptionRoute: typeof MasterOperationExceptionRoute
  MasterOperationFieldExecutiveRoute: typeof MasterOperationFieldExecutiveRoute
  MasterOperationPinCodeRoute: typeof MasterOperationPinCodeRoute
  MasterOperationServiceMappingRoute: typeof MasterOperationServiceMappingRoute
  MasterSalesBankMasterRoute: typeof MasterSalesBankMasterRoute
  MasterSalesChargesMasterRoute: typeof MasterSalesChargesMasterRoute
  MasterSalesContentRoute: typeof MasterSalesContentRoute
  MasterSalesCountryRoute: typeof MasterSalesCountryRoute
  MasterSalesDestinationRoute: typeof MasterSalesDestinationRoute
  MasterSalesFlightRoute: typeof MasterSalesFlightRoute
  MasterSalesIndustryRoute: typeof MasterSalesIndustryRoute
  MasterSalesInstructionRoute: typeof MasterSalesInstructionRoute
  MasterSalesLocalBranchRoute: typeof MasterSalesLocalBranchRoute
  MasterSalesProductRoute: typeof MasterSalesProductRoute
  MasterSalesProductTypeRoute: typeof MasterSalesProductTypeRoute
  MasterSalesSalesExecutiveRoute: typeof MasterSalesSalesExecutiveRoute
  MasterSalesServiceCenterRoute: typeof MasterSalesServiceCenterRoute
  MasterSalesStateRoute: typeof MasterSalesStateRoute
  MasterSalesZoneRoute: typeof MasterSalesZoneRoute
  MasterVendorVendorRoute: typeof MasterVendorVendorRoute
  MasterVendorVendorContractRoute: typeof MasterVendorVendorContractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/pickup-inscan': {
      id: '/transaction/pickup-inscan'
      path: '/transaction/pickup-inscan'
      fullPath: '/transaction/pickup-inscan'
      preLoaderRoute: typeof TransactionPickupInscanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/pickup': {
      id: '/transaction/pickup'
      path: '/transaction/pickup'
      fullPath: '/transaction/pickup'
      preLoaderRoute: typeof TransactionPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/manifest-view': {
      id: '/transaction/manifest-view'
      path: '/transaction/manifest-view'
      fullPath: '/transaction/manifest-view'
      preLoaderRoute: typeof TransactionManifestViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/manifest-scan': {
      id: '/transaction/manifest-scan'
      path: '/transaction/manifest-scan'
      fullPath: '/transaction/manifest-scan'
      preLoaderRoute: typeof TransactionManifestScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/manifest-in-scan': {
      id: '/transaction/manifest-in-scan'
      path: '/transaction/manifest-in-scan'
      fullPath: '/transaction/manifest-in-scan'
      preLoaderRoute: typeof TransactionManifestInScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/awb-entry': {
      id: '/transaction/awb-entry'
      path: '/transaction/awb-entry'
      fullPath: '/transaction/awb-entry'
      preLoaderRoute: typeof TransactionAwbEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$': {
      id: '/transaction/$'
      path: '/transaction/$'
      fullPath: '/transaction/$'
      preLoaderRoute: typeof TransactionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$': {
      id: '/reports/$'
      path: '/reports/$'
      fullPath: '/reports/$'
      preLoaderRoute: typeof ReportsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/$': {
      id: '/master/$'
      path: '/master/$'
      fullPath: '/master/$'
      preLoaderRoute: typeof MasterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/vendor/vendor-contract': {
      id: '/master/vendor/vendor-contract'
      path: '/master/vendor/vendor-contract'
      fullPath: '/master/vendor/vendor-contract'
      preLoaderRoute: typeof MasterVendorVendorContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/vendor/vendor': {
      id: '/master/vendor/vendor'
      path: '/master/vendor/vendor'
      fullPath: '/master/vendor/vendor'
      preLoaderRoute: typeof MasterVendorVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/zone': {
      id: '/master/sales/zone'
      path: '/master/sales/zone'
      fullPath: '/master/sales/zone'
      preLoaderRoute: typeof MasterSalesZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/state': {
      id: '/master/sales/state'
      path: '/master/sales/state'
      fullPath: '/master/sales/state'
      preLoaderRoute: typeof MasterSalesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/service-center': {
      id: '/master/sales/service-center'
      path: '/master/sales/service-center'
      fullPath: '/master/sales/service-center'
      preLoaderRoute: typeof MasterSalesServiceCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/sales-executive': {
      id: '/master/sales/sales-executive'
      path: '/master/sales/sales-executive'
      fullPath: '/master/sales/sales-executive'
      preLoaderRoute: typeof MasterSalesSalesExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/product-type': {
      id: '/master/sales/product-type'
      path: '/master/sales/product-type'
      fullPath: '/master/sales/product-type'
      preLoaderRoute: typeof MasterSalesProductTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/product': {
      id: '/master/sales/product'
      path: '/master/sales/product'
      fullPath: '/master/sales/product'
      preLoaderRoute: typeof MasterSalesProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/local-branch': {
      id: '/master/sales/local-branch'
      path: '/master/sales/local-branch'
      fullPath: '/master/sales/local-branch'
      preLoaderRoute: typeof MasterSalesLocalBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/instruction': {
      id: '/master/sales/instruction'
      path: '/master/sales/instruction'
      fullPath: '/master/sales/instruction'
      preLoaderRoute: typeof MasterSalesInstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/industry': {
      id: '/master/sales/industry'
      path: '/master/sales/industry'
      fullPath: '/master/sales/industry'
      preLoaderRoute: typeof MasterSalesIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/flight': {
      id: '/master/sales/flight'
      path: '/master/sales/flight'
      fullPath: '/master/sales/flight'
      preLoaderRoute: typeof MasterSalesFlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/destination': {
      id: '/master/sales/destination'
      path: '/master/sales/destination'
      fullPath: '/master/sales/destination'
      preLoaderRoute: typeof MasterSalesDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/country': {
      id: '/master/sales/country'
      path: '/master/sales/country'
      fullPath: '/master/sales/country'
      preLoaderRoute: typeof MasterSalesCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/content': {
      id: '/master/sales/content'
      path: '/master/sales/content'
      fullPath: '/master/sales/content'
      preLoaderRoute: typeof MasterSalesContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/charges-master': {
      id: '/master/sales/charges-master'
      path: '/master/sales/charges-master'
      fullPath: '/master/sales/charges-master'
      preLoaderRoute: typeof MasterSalesChargesMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/sales/bank-master': {
      id: '/master/sales/bank-master'
      path: '/master/sales/bank-master'
      fullPath: '/master/sales/bank-master'
      preLoaderRoute: typeof MasterSalesBankMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/operation/service-mapping': {
      id: '/master/operation/service-mapping'
      path: '/master/operation/service-mapping'
      fullPath: '/master/operation/service-mapping'
      preLoaderRoute: typeof MasterOperationServiceMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/operation/pin-code': {
      id: '/master/operation/pin-code'
      path: '/master/operation/pin-code'
      fullPath: '/master/operation/pin-code'
      preLoaderRoute: typeof MasterOperationPinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/operation/field-executive': {
      id: '/master/operation/field-executive'
      path: '/master/operation/field-executive'
      fullPath: '/master/operation/field-executive'
      preLoaderRoute: typeof MasterOperationFieldExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/operation/exception': {
      id: '/master/operation/exception'
      path: '/master/operation/exception'
      fullPath: '/master/operation/exception'
      preLoaderRoute: typeof MasterOperationExceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/operation/country-pincodes': {
      id: '/master/operation/country-pincodes'
      path: '/master/operation/country-pincodes'
      fullPath: '/master/operation/country-pincodes'
      preLoaderRoute: typeof MasterOperationCountryPincodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/operation/area': {
      id: '/master/operation/area'
      path: '/master/operation/area'
      fullPath: '/master/operation/area'
      preLoaderRoute: typeof MasterOperationAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/operation/airline': {
      id: '/master/operation/airline'
      path: '/master/operation/airline'
      fullPath: '/master/operation/airline'
      preLoaderRoute: typeof MasterOperationAirlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/customer/shipper': {
      id: '/master/customer/shipper'
      path: '/master/customer/shipper'
      fullPath: '/master/customer/shipper'
      preLoaderRoute: typeof MasterCustomerShipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/customer/expense': {
      id: '/master/customer/expense'
      path: '/master/customer/expense'
      fullPath: '/master/customer/expense'
      preLoaderRoute: typeof MasterCustomerExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/customer/customer-rate': {
      id: '/master/customer/customer-rate'
      path: '/master/customer/customer-rate'
      fullPath: '/master/customer/customer-rate'
      preLoaderRoute: typeof MasterCustomerCustomerRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/customer/customer': {
      id: '/master/customer/customer'
      path: '/master/customer/customer'
      fullPath: '/master/customer/customer'
      preLoaderRoute: typeof MasterCustomerCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/customer/consignee': {
      id: '/master/customer/consignee'
      path: '/master/customer/consignee'
      fullPath: '/master/customer/consignee'
      preLoaderRoute: typeof MasterCustomerConsigneeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  MasterSplatRoute: MasterSplatRoute,
  ReportsSplatRoute: ReportsSplatRoute,
  TransactionSplatRoute: TransactionSplatRoute,
  TransactionAwbEntryRoute: TransactionAwbEntryRoute,
  TransactionManifestInScanRoute: TransactionManifestInScanRoute,
  TransactionManifestScanRoute: TransactionManifestScanRoute,
  TransactionManifestViewRoute: TransactionManifestViewRoute,
  TransactionPickupRoute: TransactionPickupRoute,
  TransactionPickupInscanRoute: TransactionPickupInscanRoute,
  MasterCustomerConsigneeRoute: MasterCustomerConsigneeRoute,
  MasterCustomerCustomerRoute: MasterCustomerCustomerRoute,
  MasterCustomerCustomerRateRoute: MasterCustomerCustomerRateRoute,
  MasterCustomerExpenseRoute: MasterCustomerExpenseRoute,
  MasterCustomerShipperRoute: MasterCustomerShipperRoute,
  MasterOperationAirlineRoute: MasterOperationAirlineRoute,
  MasterOperationAreaRoute: MasterOperationAreaRoute,
  MasterOperationCountryPincodesRoute: MasterOperationCountryPincodesRoute,
  MasterOperationExceptionRoute: MasterOperationExceptionRoute,
  MasterOperationFieldExecutiveRoute: MasterOperationFieldExecutiveRoute,
  MasterOperationPinCodeRoute: MasterOperationPinCodeRoute,
  MasterOperationServiceMappingRoute: MasterOperationServiceMappingRoute,
  MasterSalesBankMasterRoute: MasterSalesBankMasterRoute,
  MasterSalesChargesMasterRoute: MasterSalesChargesMasterRoute,
  MasterSalesContentRoute: MasterSalesContentRoute,
  MasterSalesCountryRoute: MasterSalesCountryRoute,
  MasterSalesDestinationRoute: MasterSalesDestinationRoute,
  MasterSalesFlightRoute: MasterSalesFlightRoute,
  MasterSalesIndustryRoute: MasterSalesIndustryRoute,
  MasterSalesInstructionRoute: MasterSalesInstructionRoute,
  MasterSalesLocalBranchRoute: MasterSalesLocalBranchRoute,
  MasterSalesProductRoute: MasterSalesProductRoute,
  MasterSalesProductTypeRoute: MasterSalesProductTypeRoute,
  MasterSalesSalesExecutiveRoute: MasterSalesSalesExecutiveRoute,
  MasterSalesServiceCenterRoute: MasterSalesServiceCenterRoute,
  MasterSalesStateRoute: MasterSalesStateRoute,
  MasterSalesZoneRoute: MasterSalesZoneRoute,
  MasterVendorVendorRoute: MasterVendorVendorRoute,
  MasterVendorVendorContractRoute: MasterVendorVendorContractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
