-- ===========================================================================
-- 0010  permission_modules seed (GENERATED — do not edit by hand)
-- ---------------------------------------------------------------------------
-- Source: Access Rights screen (src/routes/utility.users.access-rights.tsx).
-- Generator: supabase/tests/gen_permission_modules.mjs
-- The screen lists 169 entries but "Scan Report" appears twice in REPORTS, so
-- there are 168 UNIQUE modules (1 duplicate collapsed by slug).
-- Idempotent: ON CONFLICT (slug) keeps rows current.
-- ===========================================================================

insert into public.permission_modules (slug, section, name, under_menu, sort_order) values
  ('mst.product-master', 'MASTERS', 'Product Master', 'Masters', 1),
  ('mst.zone-master', 'MASTERS', 'Zone Master', 'Masters', 2),
  ('mst.country-master', 'MASTERS', 'Country Master', 'Masters', 3),
  ('mst.customer-master-edit-contract-amount', 'MASTERS', 'Customer Master Edit Contract Amount', 'Masters', 4),
  ('mst.unit-master', 'MASTERS', 'Unit Master', 'Masters', 5),
  ('mst.destination-master', 'MASTERS', 'Destination Master', 'Masters', 6),
  ('mst.service-center-master', 'MASTERS', 'Service Center Master', 'Masters', 7),
  ('mst.state-master', 'MASTERS', 'State Master', 'Masters', 8),
  ('mst.sales-executive-master', 'MASTERS', 'Sales Executive Master', 'Masters', 9),
  ('mst.industry-master', 'MASTERS', 'Industry Master', 'Masters', 10),
  ('mst.flight-no-master', 'MASTERS', 'Flight No Master', 'Masters', 11),
  ('mst.product-type', 'MASTERS', 'Product Type', 'Masters', 12),
  ('mst.content-master', 'MASTERS', 'Content Master', 'Masters', 13),
  ('mst.instruction-master', 'MASTERS', 'Instruction Master', 'Masters', 14),
  ('mst.local-branch-master', 'MASTERS', 'Local Branch Master', 'Masters', 15),
  ('mst.charge-master', 'MASTERS', 'Charge Master', 'Masters', 16),
  ('mst.bank-master', 'MASTERS', 'Bank Master', 'Masters', 17),
  ('mst.customer-master', 'MASTERS', 'Customer Master', 'Masters', 18),
  ('mst.customer-contract-master', 'MASTERS', 'Customer Contract Master', 'Masters', 19),
  ('mst.consignee-master', 'MASTERS', 'Consignee Master', 'Masters', 20),
  ('mst.shipper-master', 'MASTERS', 'Shipper Master', 'Masters', 21),
  ('mst.expense-master', 'MASTERS', 'Expense Master', 'Masters', 22),
  ('mst.vendor-master', 'MASTERS', 'Vendor Master', 'Masters', 23),
  ('mst.vendor-contract-master', 'MASTERS', 'Vendor Contract Master', 'Masters', 24),
  ('mst.service-mapping', 'MASTERS', 'Service Mapping', 'Masters', 25),
  ('mst.field-executive-master', 'MASTERS', 'Field Executive Master', 'Masters', 26),
  ('mst.delivery-routes-master', 'MASTERS', 'Delivery Routes Master', 'Masters', 27),
  ('mst.area-master', 'MASTERS', 'Area Master', 'Masters', 28),
  ('mst.delivery-exception-master', 'MASTERS', 'Delivery Exception Master', 'Masters', 29),
  ('mst.airlines', 'MASTERS', 'Airlines', 'Masters', 30),
  ('mst.country-pincodes', 'MASTERS', 'Country Pincodes', 'Masters', 31),
  ('txn.pickup', 'TRANSACTION', 'Pickup', 'Entry', 32),
  ('txn.pickup-insacn', 'TRANSACTION', 'Pickup Insacn', 'Entry', 33),
  ('txn.allow-modify-delivered-entry', 'TRANSACTION', 'Allow Modify Delivered Entry', 'Entry', 34),
  ('txn.awb-entry', 'TRANSACTION', 'AWB Entry', 'Entry', 35),
  ('txn.awb-entry-allow-previous-date-entry', 'TRANSACTION', 'AWB Entry Allow Previous Date Entry', 'Entry', 36),
  ('txn.awb-entry-change-volumetric-weight-divide', 'TRANSACTION', 'AWB Entry Change Volumetric Weight Divide', 'Entry', 37),
  ('txn.awb-entry-display-amount', 'TRANSACTION', 'AWB Entry Display Amount', 'Entry', 38),
  ('txn.awb-entry-display-cash-receipt-details', 'TRANSACTION', 'AWB Entry Display Cash Receipt Details', 'Entry', 39),
  ('txn.awb-entry-display-vendor-amount', 'TRANSACTION', 'AWB Entry Display Vendor Amount', 'Entry', 40),
  ('txn.awb-entry-edit-amount', 'TRANSACTION', 'AWB Entry Edit Amount', 'Entry', 41),
  ('txn.awb-entry-file-setup', 'TRANSACTION', 'Awb Entry File Setup', 'Entry', 42),
  ('txn.awb-entry-lock-option', 'TRANSACTION', 'AWB Entry Lock Option', 'Entry', 43),
  ('txn.awb-entry-modify-after-invoice-generated', 'TRANSACTION', 'AWB Entry Modify after Invoice Generated', 'Entry', 44),
  ('txn.awb-entry-modify-after-manifest-generated', 'TRANSACTION', 'AWB Entry Modify after Manifest Generated', 'Entry', 45),
  ('txn.awb-entry-modify-customer-code-entryby-customer', 'TRANSACTION', 'AWB Entry Modify Customer Code-Entryby Customer', 'Entry', 46),
  ('txn.awb-entry-void-cancel', 'TRANSACTION', 'AWB Entry VOID/Cancel', 'Entry', 47),
  ('txn.awb-weight-change-access', 'TRANSACTION', 'AWB Weight Change Access', 'Entry', 48),
  ('txn.freight-amount-edit', 'TRANSACTION', 'Freight Amount Edit', 'Entry', 49),
  ('txn.modify-amount-edit-entry', 'TRANSACTION', 'Modify Amount Edit Entry', 'Entry', 50),
  ('txn.obc-entry-lock-unlock', 'TRANSACTION', 'OBC Entry Lock/UnLock', 'Entry', 51),
  ('txn.performa-invoice', 'TRANSACTION', 'Performa Invoice', 'Entry', 52),
  ('txn.pod-entry-ok-update', 'TRANSACTION', 'POD Entry OK Update', 'Entry', 53),
  ('txn.shipment-details', 'TRANSACTION', 'shipment details', 'Entry', 54),
  ('txn.manifest-scan', 'TRANSACTION', 'Manifest Scan', 'Entry', 55),
  ('txn.manifest-in-scan', 'TRANSACTION', 'Manifest In Scan', 'Entry', 56),
  ('txn.update-manifest', 'TRANSACTION', 'Update Manifest', 'Entry', 57),
  ('txn.drs-scan', 'TRANSACTION', 'Drs Scan', 'Entry', 58),
  ('txn.bagging', 'TRANSACTION', 'Bagging', 'Entry', 59),
  ('txn.un-delivery-scan', 'TRANSACTION', 'Un-Delivery Scan', 'Entry', 60),
  ('txn.miss-route-scan', 'TRANSACTION', 'Miss Route Scan', 'Entry', 61),
  ('txn.transfer-run', 'TRANSACTION', 'Transfer Run', 'Entry', 62),
  ('txn.obc-entry', 'TRANSACTION', 'OBC Entry', 'Entry', 63),
  ('txn.awb-query', 'TRANSACTION', 'Awb Query', 'Entry', 64),
  ('txn.forwarding-updation', 'TRANSACTION', 'Forwarding Updation', 'Entry', 65),
  ('txn.awb-query-comment-update', 'TRANSACTION', 'AWB Query Comment Update', 'Entry', 66),
  ('txn.awb-query-progress-update', 'TRANSACTION', 'AWB Query Progress Update', 'Entry', 67),
  ('txn.progress-comments-update', 'TRANSACTION', 'Progress / Comments Update', 'Entry', 68),
  ('txn.kyc-tracking', 'TRANSACTION', 'KYC Tracking', 'Entry', 69),
  ('txn.awb-hold-unhold', 'TRANSACTION', 'AWB Hold Unhold', 'Entry', 70),
  ('txn.entry-lock-update', 'TRANSACTION', 'Entry Lock Update', 'Entry', 71),
  ('txn.update-record', 'TRANSACTION', 'Update Record', 'Entry', 72),
  ('txn.expense-authorize', 'TRANSACTION', 'Expense Authorize', 'Entry', 73),
  ('txn.receipt-adjustment', 'TRANSACTION', 'Receipt Adjustment', 'Entry', 74),
  ('txn.receipt-entry', 'TRANSACTION', 'Receipt Entry', 'Entry', 75),
  ('txn.expense-entry', 'TRANSACTION', 'Expense Entry', 'Entry', 76),
  ('txn.debit-note', 'TRANSACTION', 'Debit Note', 'Entry', 77),
  ('txn.credit-note', 'TRANSACTION', 'Credit Note', 'Entry', 78),
  ('txn.customer-pay', 'TRANSACTION', 'Customer Pay', 'Entry', 79),
  ('txn.pickup-cancel', 'TRANSACTION', 'Pickup Cancel', 'Entry', 80),
  ('txn.pod-to-excel', 'TRANSACTION', 'Pod To Excel', 'Entry', 81),
  ('txn.vendor-rate-compare', 'TRANSACTION', 'Vendor Rate Compare', 'Entry', 82),
  ('txn.customerratecompare', 'TRANSACTION', 'CustomerRateCompare', 'Entry', 83),
  ('txn.opertation-dashboard', 'TRANSACTION', 'Opertation Dashboard', 'Entry', 84),
  ('txn.sales-dashboard', 'TRANSACTION', 'Sales Dashboard', 'Entry', 85),
  ('doc.invoice-cancel-after-irn-generated', 'DOCUMENTS', 'Invoice Cancel After IRN Generated', 'Documents', 86),
  ('doc.generate-invoice', 'DOCUMENTS', 'Generate Invoice', 'Documents', 87),
  ('doc.print-invoice', 'DOCUMENTS', 'Print Invoice', 'Documents', 88),
  ('doc.allow-invoice-date-to-change', 'DOCUMENTS', 'Allow Invoice Date To Change', 'Documents', 89),
  ('doc.invoice-finalise', 'DOCUMENTS', 'Invoice Finalise', 'Documents', 90),
  ('doc.invoice-irn-generation', 'DOCUMENTS', 'Invoice IRN Generation', 'Documents', 91),
  ('rpt.action-log', 'REPORTS', 'Action Log', 'Reports', 92),
  ('rpt.awb-printing', 'REPORTS', 'AWB Printing', 'Reports', 93),
  ('rpt.bag-wise-detail-print', 'REPORTS', 'Bag wise Detail Print', 'Reports', 94),
  ('rpt.bagging-report', 'REPORTS', 'Bagging Report', 'Reports', 95),
  ('rpt.billing-report', 'REPORTS', 'Billing Report', 'Reports', 96),
  ('rpt.cash-collection-report', 'REPORTS', 'Cash Collection Report', 'Reports', 97),
  ('rpt.cod-report', 'REPORTS', 'COD Report', 'Reports', 98),
  ('rpt.comment-view-report', 'REPORTS', 'Comment View Report', 'Reports', 99),
  ('rpt.customer-awb-stock-report', 'REPORTS', 'Customer AWB Stock Report', 'Reports', 100),
  ('rpt.customer-register-profit', 'REPORTS', 'Customer Register / Profit', 'Reports', 101),
  ('rpt.customer-summary', 'REPORTS', 'Customer Summary', 'Reports', 102),
  ('rpt.daily-report', 'REPORTS', 'Daily Report', 'Reports', 103),
  ('rpt.delivery-status-report', 'REPORTS', 'Delivery Status Report', 'Reports', 104),
  ('rpt.destination-summary-report', 'REPORTS', 'Destination Summary Report', 'Reports', 105),
  ('rpt.drs-report', 'REPORTS', 'DRS Report', 'Reports', 106),
  ('rpt.edi-csb-files', 'REPORTS', 'EDI CSB Files', 'Reports', 107),
  ('rpt.forwarding-no-missing-report', 'REPORTS', 'Forwarding No Missing Report', 'Reports', 108),
  ('rpt.forwarding-report', 'REPORTS', 'Forwarding Report', 'Reports', 109),
  ('rpt.invoice-report', 'REPORTS', 'Invoice Report', 'Reports', 110),
  ('rpt.location-summary', 'REPORTS', 'Location Summary', 'Reports', 111),
  ('rpt.login-log', 'REPORTS', 'Login Log', 'Reports', 112),
  ('rpt.manifest-pod-report', 'REPORTS', 'Manifest POD Report', 'Reports', 113),
  ('rpt.manifest-report', 'REPORTS', 'Manifest Report', 'Reports', 114),
  ('rpt.mis-report', 'REPORTS', 'MIS Report', 'Reports', 115),
  ('rpt.obc-report-checklist', 'REPORTS', 'OBC Report / Checklist', 'Reports', 116),
  ('rpt.ok-delivery', 'REPORTS', 'OK Delivery', 'Reports', 117),
  ('rpt.operation-report', 'REPORTS', 'Operation Report', 'Reports', 118),
  ('rpt.product-summary', 'REPORTS', 'Product Summary', 'Reports', 119),
  ('rpt.sales-executive-wise-sales-report', 'REPORTS', 'Sales Executive Wise Sales Report', 'Reports', 120),
  ('rpt.scan-report', 'REPORTS', 'Scan Report', 'Reports', 121),
  ('rpt.tariff-rate-report', 'REPORTS', 'Tariff Rate Report', 'Reports', 122),
  ('rpt.tax-report', 'REPORTS', 'Tax Report', 'Reports', 123),
  ('rpt.unassigned-drs-report', 'REPORTS', 'Unassigned DRS Report', 'Reports', 124),
  ('rpt.unassigned-manifest-report', 'REPORTS', 'Unassigned Manifest Report', 'Reports', 125),
  ('rpt.unassigned-obc-report', 'REPORTS', 'Unassigned OBC Report', 'Reports', 126),
  ('rpt.undelivery-report', 'REPORTS', 'Undelivery Report', 'Reports', 127),
  ('rpt.user-analysis-report', 'REPORTS', 'User Analysis Report', 'Reports', 128),
  ('rpt.user-entry-log-report', 'REPORTS', 'User Entry Log Report', 'Reports', 129),
  ('rpt.vendor-profit-report', 'REPORTS', 'Vendor Profit Report', 'Reports', 130),
  ('rpt.void-report', 'REPORTS', 'Void Report', 'Reports', 131),
  ('rpt.volumetric-weight-report', 'REPORTS', 'Volumetric Weight Report', 'Reports', 132),
  ('rpt.zero-report', 'REPORTS', 'Zero Report', 'Reports', 133),
  ('rpt.statement-report', 'REPORTS', 'Statement Report', 'Reports', 134),
  ('rpt.awb-report', 'REPORTS', 'AWB Report', 'Reports', 135),
  ('rpt.reports-allow-report-field-selection', 'REPORTS', 'Reports Allow Report Field Selection', 'Reports', 136),
  ('rpt.ar-report', 'REPORTS', 'AR Report', 'Reports', 138),
  ('utl.serviceable-pincode', 'UTILITIES', 'Serviceable Pincode', 'Utilities', 139),
  ('utl.notification', 'UTILITIES', 'Notification', 'Utilities', 140),
  ('utl.fuel-setup', 'UTILITIES', 'Fuel Setup', 'Utilities', 141),
  ('utl.user-setup', 'UTILITIES', 'User Setup', 'Utilities', 142),
  ('utl.access-rights', 'UTILITIES', 'Access Rights', 'Utilities', 143),
  ('utl.awb-merging', 'UTILITIES', 'AWB Merging', 'Utilities', 144),
  ('utl.loggedin-users', 'UTILITIES', 'LoggedIn Users', 'Utilities', 145),
  ('utl.pod-merging', 'UTILITIES', 'Pod Merging', 'Utilities', 146),
  ('utl.forwarding-merging', 'UTILITIES', 'Forwarding Merging', 'Utilities', 147),
  ('utl.customer-awb-stock-merging', 'UTILITIES', 'Customer AWB Stock Merging', 'Utilities', 148),
  ('utl.data-import', 'UTILITIES', 'Data Import', 'Utilities', 149),
  ('utl.other-charges-import', 'UTILITIES', 'Other Charges Import', 'Utilities', 150),
  ('utl.data-updation', 'UTILITIES', 'Data Updation', 'Utilities', 151),
  ('utl.tax-surcharge-setup', 'UTILITIES', 'Tax & Surcharge Setup', 'Utilities', 152),
  ('utl.xpresion-setup', 'UTILITIES', 'Xpresion Setup', 'Utilities', 153),
  ('utl.rate-update', 'UTILITIES', 'Rate Update', 'Utilities', 154),
  ('utl.zone-update', 'UTILITIES', 'Zone Update', 'Utilities', 155),
  ('utl.rate-import', 'UTILITIES', 'Rate Import', 'Utilities', 156),
  ('mob.awbentry', 'MOBILE', 'AWBEntry', 'MobileApplication', 157),
  ('mob.delivery', 'MOBILE', 'Delivery', 'MobileApplication', 158),
  ('mob.drs', 'MOBILE', 'DRS', 'MobileApplication', 159),
  ('mob.manifest', 'MOBILE', 'Manifest', 'MobileApplication', 160),
  ('mob.manifestinscan', 'MOBILE', 'ManifestInscan', 'MobileApplication', 161),
  ('mob.pickup', 'MOBILE', 'Pickup', 'MobileApplication', 162),
  ('mob.pickupinscan', 'MOBILE', 'PickupInScan', 'MobileApplication', 163),
  ('mob.pod-entry', 'MOBILE', 'POD Entry', 'MobileApplication', 164),
  ('mob.predrs', 'MOBILE', 'PreDrs', 'MobileApplication', 165),
  ('mob.report', 'MOBILE', 'Report', 'MobileApplication', 166),
  ('mob.track', 'MOBILE', 'TRACK', 'MobileApplication', 167),
  ('mob.pickup-return', 'MOBILE', 'Pickup Return', 'MobileApplication', 168),
  ('mob.scan-print', 'MOBILE', 'Scan & Print', 'MobileApplication', 169)
on conflict (slug) do update
  set section    = excluded.section,
      name       = excluded.name,
      under_menu = excluded.under_menu,
      sort_order = excluded.sort_order,
      is_active  = true,
      updated_at = now();
