-- Internal AWB Label is generated by the app (SYSTEM), not vendor API.
-- Show it as waiting until generated, instead of "Not required".

create or replace function public.list_shipment_documents(p_shipment_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, app
as $$
declare
  v_tenant uuid;
  v_s public.shipments;
  v_rows jsonb;
begin
  select t into v_tenant from (select app.user_tenant_ids() as t) s limit 1;
  if v_tenant is null then
    raise exception 'No tenant context' using errcode = '42501';
  end if;

  select * into v_s
  from public.shipments
  where id = p_shipment_id and tenant_id = v_tenant and deleted_at is null;
  if not found then
    raise exception 'Shipment not found' using errcode = 'P0002';
  end if;

  with catalog(document_type, title, default_status) as (
    values
      ('AUTHORITY_LETTER', 'Authority Letter', 'WAITING'),
      ('AWB_LABEL', 'AWB Label', 'WAITING'),
      ('INVOICE', 'Invoice', 'NOT_REQUIRED'),
      ('VENDOR_AWB', 'Vendor AWB', 'WAITING'),
      ('VENDOR_INVOICE', 'Vendor Invoice', 'WAITING'),
      ('KYC', 'KYC', 'NOT_REQUIRED')
  ),
  latest as (
    select distinct on (d.document_type)
      d.id, d.document_type, d.source, d.vendor, d.file_name, d.file_url,
      d.content_b64, d.mime_type, d.file_size, d.version, d.status,
      d.created_at, d.updated_at, d.raw_meta
    from public.shipment_documents d
    where d.tenant_id = v_tenant
      and d.shipment_id = p_shipment_id
      and d.deleted_at is null
    order by d.document_type, d.version desc, d.created_at desc
  )
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'type', c.document_type,
      'title', c.title,
      'status', case
        when l.id is null then c.default_status
        when (l.file_url is not null or l.content_b64 is not null) then 'AVAILABLE'
        else coalesce(l.status, c.default_status)
      end,
      'id', l.id,
      'url', l.file_url,
      'content_b64', l.content_b64,
      'fileName', coalesce(l.file_name, c.title),
      'mimeType', coalesce(l.mime_type, 'application/pdf'),
      'fileSize', l.file_size,
      'version', l.version,
      'source', l.source,
      'vendor', l.vendor,
      'createdAt', l.created_at,
      'updatedAt', l.updated_at,
      'available', (l.file_url is not null or l.content_b64 is not null)
    )
    order by array_position(
      array['AUTHORITY_LETTER','AWB_LABEL','INVOICE','VENDOR_AWB','VENDOR_INVOICE','KYC'],
      c.document_type
    )
  ), '[]'::jsonb)
  into v_rows
  from catalog c
  left join latest l on l.document_type = c.document_type;

  return v_rows;
end;
$$;
